# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 'default'

variables: 

  MyRunNumber: '1.0.$(Build.BuildNumber)'
  buildConfiguration: 'Release'


steps:
- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'sonar'
    scannerMode: 'MSBuild'
    projectKey: 'hello_hello_AZAgmfdPWa754p4Pk2fq'

- script: |
    #!/bin/bash
    # The Azure DevOps' SonarQube plugin automatically adds `sonar.branch.name` for us, but we don't want this to be set, since we're analyzing a pull request.
    echo "Original SONARQUBE_SCANNER_PARAMS: $SONARQUBE_SCANNER_PARAMS"
    # Convert SONARQUBE_SCANNER_PARAMS to a JSON file
    echo $SONARQUBE_SCANNER_PARAMS > sonarParams.json
    # Remove the sonar.branch.name key
    jq 'del(.["sonar.branch.name"])' sonarParams.json > updatedSonarParams.json
    # Convert the updated JSON back to a string and set the environment variable
    export SONARQUBE_SCANNER_PARAMS=$(cat updatedSonarParams.json | jq -c .)
    echo "Updated SONARQUBE_SCANNER_PARAMS: $SONARQUBE_SCANNER_PARAMS"
  displayName: 'Remove sonar.branch.name from SonarQube parameters'
  env:
    SONARQUBE_SCANNER_PARAMS: $(SONARQUBE_SCANNER_PARAMS)
- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: 'build'
    projects: '**/*.csproj'


- task: SonarQubeAnalyze@6
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'


- task: DotNetCoreCLI@2
  displayName: pack
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'MyRunNumber'

- task: DotNetCoreCLI@2
  displayName: push
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '3ee772fe-0f57-4164-b70b-438a74a262b1/a1c0f62b-b484-4828-8150-3e6ea1fd60e3'
- script: echo $(MyRunNumber)
- task: SonarQubePublish@6
  inputs:
    pollingTimeoutSec: '300'