# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 'default'

variables: 
  Major: '1'
  Minor: '1'
  revision: $[counter(variables['Minor'], 1)]
  MyRunNumber: '$(Major).$(Minor).$(revision)'
  buildConfiguration: 'Release'


steps:
- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'sonar'
    scannerMode: 'MSBuild'
    projectKey: 'sqa_ad234c6b24974efb6d24ff997582abccef57f3a3'


- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: '**/*.csproj'


- task: SonarQubeAnalyze@6
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'


- task: DotNetCoreCLI@2
  displayName: pack
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    configuration: $(buildConfiguration)
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'MyRunNumber'

- task: DotNetCoreCLI@2
  displayName: push
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '3ee772fe-0f57-4164-b70b-438a74a262b1/a1c0f62b-b484-4828-8150-3e6ea1fd60e3'
- script: echo $(MyRunNumber)
- task: SonarQubePublish@6
  inputs:
    pollingTimeoutSec: '300'