trigger:
- main

pool: 'default'

variables: 
  MyRunNumber: '1.0.$(Build.BuildNumber)'
  buildConfiguration: 'Release'

steps:
- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'sonar'
    scannerMode: 'MSBuild'
    projectKey: 'hello_hello_AZAgmfdPWa754p4Pk2fq'
    projectName: 'hello'
    projectVersion: '$(Build.BuildNumber)'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.branch.name=main

- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: SonarQubeAnalyze@6
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: DotNetCoreCLI@2
  displayName: pack
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'MyRunNumber'

- task: DotNetCoreCLI@2
  displayName: push
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '3ee772fe-0f57-4164-b70b-438a74a262b1/a1c0f62b-b484-4828-8150-3e6ea1fd60e3'

- script: echo $(MyRunNumber)

- task: SonarQubePublish@6
  inputs:
    pollingTimeoutSec: '300'
